# -*- coding: utf-8 -*-
"""ola_mundo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17XqRdVfnRGhJyYYqgFOE2-l9l5cKsTvi
"""

print("Olá, mundo!")